### ISSUE TITLE
The media palette is broken

### ISSUE THREAD

**Issue by lionirdeadman** [sugarlabs/turtleart-activity#84]
https://user-images.githubusercontent.com/481418/118795052-30d05000-b868-11eb-819e-0895c2752e7b.png

```log
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1241, in _buttonpress_cb
    self.button_press(
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1311, in button_press
    elif self._check_for_anything_else(spr, x, y):
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1624, in _check_for_anything_else
    self._select_category(spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1794, in _select_category
    self.show_palette(i)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 987, in show_palette
    self.show_toolbar_palette(n)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1097, in show_toolbar_palette
    self.palette_views[n].create(regenerate=regenerate, show=show)
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 64, in create
    self._create_proto_blocks()
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 198, in _create_proto_blocks
    self._proto_skin(name + 'small', self.blocks[-1].spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 211, in _proto_skin
    x, y = self._turtle_window.calc_image_offset(name, spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 4863, in calc_image_offset
    iw = self.media_shapes[name].get_width()
KeyError: 'camera1small'
```

as reported on https://github.com/flathub/org.laptop.TurtleArtActivity/pull/5#issuecomment-843954442 , managed to reproduce myself.

One thing to note is it seems that clicking it the first time produces the error but going to another tab and then back to it works fine.

**Comment by Dimi20cen** [comment]
Is this issue fixed? Can't reproduce it.

**Comment by chimosky** [comment]
Seems it's been fixed as I can't reproduce it too.
